import yfinance as yf
import sys
import pandas as pd
import time

## -----while calling the script-----
# equity = sys.argv[1]
# print('equity is : ',equity)

# --------while taking the input from the console------
print('enter a equity from the following list:\n1. BlueChip \n2. IPO \n3. Growth \n4. Value \n5. Dividend_paying \n6. High_Beta \n7. Low_Beta \n8. Large_cap \n9. Mid_cap \n10. Small_cap \n11. 0.8-1.2_Beta \n')
equity = input()
print('Entered Equity  is :', equity)

start_time = time.time()

# data = yf.download(tickers='ITC.NS,BAJAJ-AUTO.NS',period='1d',group_by = 'ticker')

stocks = []
if equity == "BlueChip":
    stocks = ["BAJAJ-AUTO.NS","BALKRISIND.NS","ULTRACEMCO.NS","ASIANPAINT.NS","PIDILITIND.NS","LT.NS","NESTLEIND.NS","BRITANNIA.NS","MARICO.NS","HDFC.NS","HDFCBANK.NS","BAJAJFINSV.NS","SBIN.NS","AXISBANK.NS","SBICARD.NS","HDFCLIFE.NS","TCS.NS","INFY","TATASTEEL.NS","HINDZINC.NS","RELIANCE.NS","DIVISLAB.NS","CIPLA.NS","ADANIPORTS.NS","POWERGRID.NS","NTPC.NS"]
elif equity == "IPO":
    stocks = ["ANGELBRKG.NS","AWHCL.NS","BARBEQUE.NS","BURGERKING.NS","CHEMCON.NS","CAMS.NS","CRAFTSMAN.NS","EASEMYTRIP.NS","EQUITASBNK.NS","GLAND.NS","HAPPSTMNDS.NS","HERANBA.NS","HOMEFIRST.NS","IRFC.NS","INDIGOPNTS.NS","KALYANKJIL.NS","LXCHEM.NS","LODHA.NS","MAZDOCK.NS","BECTORFOOD.NS","MTARTECH.NS","NAZARA.NS","RAILTEL.NS","ROSSARI.NS","ROUTE.NS","STOVEKRAFT.NS","SURYODAY.NS","UTIAMC.NS"]
elif equity == "Growth":
    stocks = ["BAJAJ-AUTO.NS","BRITANNIA.NS","ITC.NS","NESTLEIND.NS","TATACONSUM.NS","UPL.NS","VOLTAS.NS","JINDALSTEL.NS","SAIL.NS","MGL.NS","TATAPOWER.NS","HCLTECH.NS","HINDALCO.NS","BIRLACORPN.NS","ALKYLAMINE.NS","CHAMBLFERT.NS","THYROCARE.NS","COCHINSHIP.NS","HAPPSTMNDS.NS"]
elif equity == "Value":
    stocks = ["ALKYLAMINE.NS","RVNL.NS","AVANTIFEED.NS","CDSL.NS","IDFC.NS","INDIANB.NS","PNBHOUSING.NS","AARTIDRUGS.NS","GRANULES.NS","JBCHEPHARM.NS","KEC.NS","RITES.NS","AMARAJABAT.NS","BALKRISIND.NS","ESCORTS.NS","CHOLAFIN.NS","MANAPPURAM.NS","SRTRANSFIN.NS","SUNTV.NS","JINDALSTEL.NS","CASTROLIND.NS","MGL.NS","TORNTPOWER.NS","IRCTC.NS","COCHINSHIP.NS","IOC.NS","HINDZINC.NS","AJANTPHARM.NS","VEDL.NS","TATASTLBSL.NS","EIDPARRY.NS","GNFC.NS","JYOTHYLAB.NS"]
elif equity == "Dividend_paying":
    stocks = ["ASIANPAINT.NS","BAJFINANCE.NS","FINCABLES.NS","HDFC.NS","INFY","ITC.NS","LAOPALA.NS","NESCO.NS","PERSISTENT.NS","PIDILITIND.NS","RELIANCE.BO","BAJAJ-AUTO.NS","CESC.NS","CHAMBLFERT.NS","NAVINFLUOR.NS","NTPC.NS","POWERGRID.NS","NHPC.NS","PETRONET.NS","GAIL.NS","ONGC.NS","IOC.NS","VEDL.NS","COALINDIA.NS","HINDPETRO","IRFC","MCX","TORNTPOWER","VSTIND","RVNL","COCHINSHIP"]
elif equity == "High_Beta":
    stocks = ["GMRINFRA.NS","AUBANK.NS","CANBK.NS","CHOLAFIN.NS","FEDERALBNK.NS","IDFCFIRSTB.NS","IBULHSGFIN.NS","L&TFH.NS","LICHSGFIN.NS","SRTRANSFIN.NS","BHEL.NS","JINDALSTEL.NS","SAIL.NS","M&M.BO","TATAMOTORS.NS","BAJFINANCE.NS","BAJAJFINSV.NS","HDFCBANK.NS","HDFC.NS","ICICIBANK.NS","INDUSINDBK.NS","HINDALCO.NS"]
elif equity == "Low_Beta":
    stocks = ["BAJAJ-AUTO.NS","AMARAJABAT.NS","CEATLTD.NS","ASIANPAINT.NS","RVNL.NS","BRITANNIA.NS","HINDUNILVR.NS","ITC.NS","NESTLEIND.NS","TATACONSUM.NS","AVANTIFEED.NS","KAJARIACER.NS","CHAMBLFERT.NS","HDFCLIFE.NS","SBILIFE.NS","MFSL.NS","CAMS.NS","MCX.NS","UTIAMC.NS","THYROCARE.NS","CUMMINSIND.NS","GMMPFAUDLR.NS","HCLTECH.NS","INFY","TCS.NS","TECHM.NS","WIPRO.NS","MINDTREE.NS","HAPPSTMNDS.NS","ROUTE.NS","MGL.NS","CIPLA.NS","DIVISLAB.NS","DRREDDY.NS","SUNPHARMA.NS","AARTIDRUGS.NS","GRANULES.NS","JBCHEPHARM.NS","TORNTPOWER.NS","KEC.NS","IRCTC.NS","RITES.NS","SRF.NS","PAGEIND.NS"]
elif equity == "Large_cap":
    stocks = ["BAJAJ-AUTO.NS","TATAMOTORS.NS","HDFCBANK.NS","ICICIBANK.NS","AXISBANK.NS","ULTRACEMCO.NS","SHREECEM.NS","PIDILITIND.NS","ASIANPAINT.NS","BAJAJFINSV.NS","SBICARD.NS","NESTLEIND.NS","BRITANNIA.NS","LT.NS","SBILIFE.NS","HDFCLIFE.NS","TCS.NS","INFY","HINDZINC.NS","JSWSTEEL.NS","TATASTEEL.NS","VEDL.NS","SUNPHARMA.NS","DIVISLAB.NS","CIPLA.NS","ADANIPORTS.NS","POWERGRID.NS","NTPC.NS","RELIANCE.NS","DMART.NS"]
elif equity == "Mid_cap":
    stocks = ["ASHOKLEY.NS","TVSMOTOR.NS","AMARAJABAT.NS","BALKRISIND.NS","ESCORTS.NS","EXIDEIND.NS","BHARATFORG.NS","BANKBARODA.NS","BANKINDIA.NS","CANBK.NS","FEDERALBNK.NS","RBLBANK.NS","UNIONBANK.NS","RAMCOCEM.NS","GMRINFRA.NS","VOLTAS.NS","BEL.NS","AUBANK.NS","CHOLAFIN.NS","IDFCFIRSTB.NS","IBULHSGFIN.NS","L&TFH.NS","MANAPPURAM.NS","RECLTD.NS","SRTRANSFIN.NS","LICHSGFIN.NS","M&MFIN.NS","MFSL.NS","PFC.NS","BATAINDIA.NS","CUMMINSIND.NS","BHEL.NS","MINDTREE.NS","COFORGE.NS","SUNTV.NS","ZEEL.NS","JINDALSTEL.NS","SAIL.NS","CASTROLIND.NS","MGL.NS","GLENMARK.NS","TATAPOWER.NS","TORNTPOWER.NS","GODREJPROP.NS","CONCOR.NS","IRCTC.NS","IDEA.NS","SRF.NS","PAGEIND.NS","APOLLOTYRE.NS"]
elif equity == "Small_cap":
    stocks = ["ALKYLAMINE.NS","NBCC.NS","RVNL.NS","AVANTIFEED.NS","KAJARIACER.NS","RADICO.NS","CHAMBLFERT.NS","CDSL.NS","CAMS.NS","MCX.NS","UTIAMC.NS","THYROCARE.NS","BDL.NS","COCHINSHIP.NS","GMMPFAUDLR.NS","GRAPHITE.NS","AFFLE.NS","HAPPSTMNDS.NS","ROUTE.NS","VAKRANGEE.NS","APLAPOLLO.NS","NATIONALUM.NS","AARTIDRUGS.NS","GRANULES.NS","JBCHEPHARM.NS","KEC.NS","RITES.NS","STLTECH.NS"]
elif equity == "0.8-1.2_Beta":
    stocks = ["EICHERMOT.NS","HEROMOTOCO.NS","MARUTI.NS","BALKRISIND.NS","ESCORTS.NS","EXIDEIND.NS","RAMCOCEM.NS","ALKYLAMINE.NS","LT.NS","NBCC.NS","VOLTAS.NS","RADICO.NS","UPL.NS","KOTAKBANK.NS","BANKINDIA.NS","RECLTD.NS","UNIONBANK.NS","CDSL.NS","IDFC.NS","PNBHOUSING.NS","BEL.NS","GRAPHITE.NS","VAKRANGEE.NS","SUNTV.NS","JSWSTEEL.NS","TATASTEEL.NS","APLAPOLLO.NS","NATIONALUM.NS","BPCL.NS","IOC.NS","RELIANCE.NS","GLENMARK.NS","ADANIPORTS.NS","NTPC.NS","POWERGRID.NS","BHARTIARTL.NS","STLTECH.NS"]

print('stocks is : ',stocks)

data = {}
for tickers in stocks:
    data[tickers] = yf.Ticker(tickers).info

finalData = []

for items in data:
    dicData = {}
    dicData['Company_Name'] = data[items]['longName']
    dicData['Current_Price'] = data[items]['currentPrice']
    dicData['Volume'] = data[items]['volume']
    dicData['Open'] = data[items]['open']
    dicData['52_Week_High'] = data[items]['fiftyTwoWeekHigh']
    dicData['52_Week_Low'] = data[items]['fiftyTwoWeekLow']
    finalData.append(dicData)
#print(data['BAJAJ-AUTO.NS']['marketCap'])
print('Check in Json Formatter: ', finalData)

df = pd.DataFrame(data = finalData)
print(df)

writer = pd.ExcelWriter('Investment Planning.xlsx', engine='xlsxwriter')
df.to_excel(writer, sheet_name=equity, index=False)
writer.save()
end_time = time.time()
print("it took this long to run (s): {}".format(end_time-start_time))